from decimal import Decimal
from typing import Protocol

from .models import Account, AccountCreate, AccountUpdate, Admin, AdminCreate, Customer, CustomerCreate, CustomerUpdate, Transaction, User


class AccountStoreProtocol(Protocol):
    def list_accounts(self) -> list[Account]: ...

    def list_for_owner(self, owner_id: int) -> list[Account]: ...

    def get(self, account_id: int) -> Account | None: ...

    def get_by_account_number(self, account_number: str) -> Account | None: ...

    def create(self, account_data: AccountCreate) -> Account: ...

    def update(self, account_id: int, account_data: AccountUpdate) -> Account | None: ...

    def save(self, account: Account) -> Account: ...

    def delete(self, account_id: int) -> bool: ...

    def deposit(self, account_id: int, amount: Decimal) -> Account | None: ...

    def withdraw(self, account_id: int, amount: Decimal) -> Account | None: ...

    def transfer(self, from_account_id: int, to_account_id: int, amount: Decimal) -> tuple[Account, Account] | None: ...

    def list_transactions(self) -> list[Transaction]: ...

    def list_transactions_for_owner(self, owner_id: int) -> list[Transaction]: ...


class UserStoreProtocol(Protocol):
    def list_customers(self) -> list[Customer]: ...

    def list_admins(self) -> list[Admin]: ...

    def get(self, user_id: int) -> User | None: ...

    def get_customer(self, user_id: int) -> Customer | None: ...

    def get_by_email(self, email: str) -> User | None: ...

    def authenticate(self, email: str, password: str) -> User | None: ...

    def create_customer(self, user_data: CustomerCreate) -> Customer: ...

    def create_admin(self, user_data: AdminCreate) -> Admin: ...

    def update_customer(self, user_id: int, user_data: CustomerUpdate) -> Customer | None: ...

    def delete_customer(self, user_id: int) -> bool: ...
